services:
  bot:
    build:
      context: .
      target: prod
    env_file:
      - ./src/config/.env.local
    ports:
      - "${HOST_PORT:-8080}:${CONTAINER_PORT:-80}"
    volumes:
      - ./data:/code/data
    restart: unless-stopped
