services:
  bot:
    build:
      context: .
      target: prod
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/code
