services:
  bot:
    build:
      context: .
      target: prod
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - ./data:/code/data
    restart: unless-stopped
    environment:
      - PYTHONPATH=/code
